FROM python:3.10

WORKDIR /app
ARG TARGET_BRANCH
ENV DEPLOYMENT=local

SHELL ["/bin/bash", "-c"]

RUN apt-get update \
&& apt-get -y install git unzip \
&& curl -LsSf https://astral.sh/uv/install.sh | sh \
&& source ${HOME}/.local/bin/env \
&& git clone https://github.com/toposoid/data-accessor-weaviate-web.git \
&& cd data-accessor-weaviate-web \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH} \
&& sed s/__##GIT_BRANCH##__/${TARGET_BRANCH}/g pyproject.toml.template > pyproject.toml \
&& uv sync \
&& uv add git+https://github.com/toposoid/toposoid-python-lib.git@${TARGET_BRANCH}#egg=ToposoidCommon
#&& sed -i s/__##GIT_BRANCH##__/${TARGET_BRANCH}/g requirements.txt \
#&& pip install --no-cache-dir --trusted-host pypi.python.org -r requirements.txt
