version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  data-accessor-weaviate-web:
    image: data-accessor-weaviate-web:0.5-SNAPSHOT
    tty: true
    environment:
      - TOPOSOID_WEAVIATE_HOST=172.30.0.2
      - TOPOSOID_WEAVIATE_PORT=8081
      - TOPOSOID_WEAVIATE_SIMILARITY_THRESHOLD=0.85
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    ports:
      - 9011:9011
    depends_on:
      - weaviate
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.21.2
    ports:
    - 8080:8080
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    volumes:
    - /var/weaviate:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-huggingface'
      HUGGINGFACE_APIKEY: ''
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'   