name: Test And Build
on:
  workflow_call:
env:
  PJ_ACTOR: toposoid
  PJ_REPO: data-accessor-weaviate-web
  PJ_BRANCH: feature
  PJ_VERSION: 0.7-SNAPSHOT
jobs:
  unit-test_data-accessor-weaviate-web-amd64:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone ${{ env.PJ_REPO }}
        uses: actions/checkout@v4
        with:
            repository: ${{ env.PJ_ACTOR }}/${{ env.PJ_REPO }}
      - name: Execute tests
        run: |
            cd ${GITHUB_WORKSPACE} && cd ../
            cd ./${{ env.PJ_REPO }}
            docker build --build-arg TARGET_BRANCH=${{ env.PJ_BRANCH }} --tag ${{ env.PJ_REPO }}:${{ env.PJ_VERSION }} -f Dockerfile-workflow .
            docker compose -f docker-compose-workflow.yml up -d
            curl --retry 10 --retry-delay 5 --retry-all-errors -X POST -H "Content-Type: application/json" -d '{}' http://localhost:8080
            docker compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && source /root/.local/bin/env && uv run pytest -v"
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v5
        with:
          images: toposoid/${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}
      - name: Login to CR
        uses: docker/login-action@v3
        with:
          username: toposoid
          password: ${{ secrets.CR_TOKEN }}
      - name: Build And Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: toposoid/${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}-amd64
          build-args: |
            TARGET_BRANCH=${{ env.PJ_BRANCH }}
